### PR TITLE
Support safe area

### PR DESCRIPTION
**Pull request by vdugnist**

### CODE REVIEW

**Comment by vdugnist** [comment]
"osx_image": "xcode7.2"
Looks like Xcode 7.2 can't compile these changes.

**Comment by k06a** [comment]
>Xcode 9.1 is available by adding `osx_image: xcode9.1` to your `.travis.yml`

https://docs.travis-ci.com/user/reference/osx/#Xcode-9.1

**Comment by k06a** [comment]
NTBR

**Comment by k06a** [comment]
@vdugnist,
```
--------------------------------------------------------------------------------
 🎉  Congrats

 🚀  MissingAnchors (0.6.0) successfully published
 📅  October 18th, 14:16
 🌎  https://cocoapods.org/pods/MissingAnchors
 👍  Tell your friends!
--------------------------------------------------------------------------------
```

**Pull request merged**
